// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: client.sql

package db

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    owner_login
) VALUES (
    $1
) RETURNING id, owner_login, created_at
`

func (q *Queries) CreateClient(ctx context.Context, ownerLogin string) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, ownerLogin)
	var i Client
	err := row.Scan(&i.ID, &i.OwnerLogin, &i.CreatedAt)
	return i, err
}
