// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: client.sql

package db

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    full_name,
    login
) VALUES (
    $1, $2
) RETURNING id, full_name, login, created_at
`

type CreateClientParams struct {
	FullName string `json:"full_name"`
	Login    string `json:"login"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, arg.FullName, arg.Login)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Login,
		&i.CreatedAt,
	)
	return i, err
}
