// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	AddDishAmount(ctx context.Context, arg AddDishAmountParams) (Dish, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateDish(ctx context.Context, arg CreateDishParams) (Dish, error)
	CreateRestaurant(ctx context.Context, name string) (Restaurant, error)
	GetDish(ctx context.Context, id int32) (Dish, error)
	ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]Restaurant, error)
	createOrder(ctx context.Context, arg createOrderParams) (Order, error)
	createOrderItem(ctx context.Context, arg createOrderItemParams) (OrderItem, error)
}

var _ Querier = (*Queries)(nil)
