// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    login,
    full_name,
    hashed_passwords
) VALUES (
    $1, $2, $3
) RETURNING login, full_name, hashed_passwords, created_at
`

type CreateUserParams struct {
	Login           string `json:"login"`
	FullName        string `json:"full_name"`
	HashedPasswords string `json:"hashed_passwords"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Login, arg.FullName, arg.HashedPasswords)
	var i User
	err := row.Scan(
		&i.Login,
		&i.FullName,
		&i.HashedPasswords,
		&i.CreatedAt,
	)
	return i, err
}
